### ISSUE TITLE
Implementation of the Media Fragment URI Recommendation

### ISSUE THREAD

**Issue by FWeinb** [davatron5000/TimeJump#7] opened 2013-04-06 18:07 UTC
There is a W3C Recommendation for defining temporal dimension of media files. Why not make this conform to this spec? 

http://www.w3.org/TR/media-frags/#naming-time

**Comment by davatron5000** [comment] 2013-04-06 18:25
Thanks for the issue. If you look through some of the other issues, some work on this is already underway. Hopefully we can match it up.

**Comment by davatron5000** [comment] 2013-04-08 14:44
Just added some commit over the weekend to put us closer to NPT compliance. The only last feature of that would be the "temporal clipping" which is a duplicate of #3, so I'll close this issue.

**Closed as completed by davatron5000** 2013-04-08 14:44 UTC
